# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

BAZEL_INSTALLER = struct(
    revision = "3.7.1",
    sha256 = "094255173f1cbf135825221a07245354ee53949a50801ff115b2082eee94aa76",
)

DEBS_TARBALL = struct(
    revision = "1606343629",
    sha256 = "9a8e729db5adf9e5b6fd7bbd33ee4fcb3889f4b1423fa0e51cdf7d58c5b3a4ad",
)
